language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

install:
  - composer install --prefer-source

before_script:
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then vendor/bin/phpcs src tests -p --standard=src/SymplifyCodingStandard/ruleset.xml --extensions=php; fi

script:
  - vendor/bin/phpunit
